StoreWebsite/Models/Cart/CartItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StoreWebsite.Models
{
    public class CartItem
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public Guid ProductId { get; set; }
        public virtual Product Product { get; set; }

        [Display(Name = "Total price")]
        public decimal TotalPrice
        {
            get
            {
                return Product != null ? Product.Price * Quantity : 0;
            }
        }

        [Required]
        public Guid UserId { get; set; }
        [Required]
        [Range(1, int.MaxValue)]
        public int Quantity { get; set; }
    }
}

StoreWebsite/Models/Cart/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace StoreWebsite.Models
{
    public class CartViewModel
    {
        public IEnumerable<CartItem> CartItems { get; set; }

        [Display(Name = "Total value")]
        public decimal TotalValue
        {
            get
            {
                return CartItems.Sum(item => item.Quantity * item.Product.Price);
            }
        }
    }
}

StoreWebsite/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreWebsite.Models;
using StoreWebsite.Services;
using StoreWebsite.Services.Users;
using StoreWebsite.Models.Orders;

namespace StoreWebsite.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        private readonly UserManager<ApplicationUser> _userManager;

        public OrdersController(IProductService productService, UserManager<ApplicationUser> userManager,
            ICartService cartService, IOrderService orderService, IUserService userService)
        {
            _productService = productService;
            _userManager = userManager;
            _cartService = cartService;
            _orderService = orderService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var orders = await _orderService.GetOrderListAsync(Guid.Parse(user.Id), new OrderFilters() { StatusCode = OrderStatus.None });

            OrderListViewModel orderList = new OrderListViewModel()
            {
                Orders = orders
            };

            return View(orderList);
        }

        public async Task<IActionResult> ChooseAddress()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            return View(user);
        }

        public async Task<IActionResult> Add(Guid addressId)
        {
            Address address = await _userService.GetAddressAsync(addressId);

            Order order = new Order() { Address = address };

            return View(order);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Add")]
        public async Task<IActionResult> AddConfirmed(Order newOrder)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var userId = Guid.Parse(user.Id);

            Order order = new Order()
            {
                Id = Guid.NewGuid(),
                OrderDate = DateTime.Now,
                Address = newOrder.Address,
                AddressId = newOrder.AddressId,
                Description = newOrder.Description,
                StatusCode = OrderStatus.New,
                UserId = userId
            };

            List<OrderDetails> orderDetails = new List<OrderDetails>();
            var cart = await _cartService.GetCartAsync(userId);

            foreach(var cartItem in cart)
            {
                orderDetails.Add(new OrderDetails()
                {
                    OrderId = order.Id,
                    ProductId = cartItem.ProductId,
                    Quantity = cartItem.Quantity
                });
            }

            bool successful = await _orderService.AddOrderAsync(order, orderDetails);
            if (!successful)
                return BadRequest(new { error = "Could not add order" });

            await _cartService.ClearCartAsync(userId);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid orderId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            Order order = await _orderService.GetOrderAsync(orderId);

            if (Guid.Parse(user.Id) != order.UserId)
            {
                return BadRequest(new { error = "No permissions to view other users' orders" });
            }

            return View(order);
        }

        public async Task<IActionResult> Cancel(Guid orderId)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            Order order = await _orderService.GetOrderAsync(orderId);

            if (Guid.Parse(user.Id) != order.UserId)
            {
                return BadRequest(new { error = "No permissions to view other users' orders" });
            }

            return View(order);
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Cancel")]
        public async Task<IActionResult> CancelConfirmed(Order cancelledOrder)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            Order order = await _orderService.GetOrderAsync(cancelledOrder.Id);

            if (order.StatusCode != OrderStatus.New)
            {
                return BadRequest(new { error = "Cannot cancel order" });
            }

            if (Guid.Parse(user.Id) != order.UserId)
            {
                return BadRequest(new { error = "No permissions to view other users' orders" });
            }

            bool successful = await _orderService.CancelOrderAsync(order);
            if (!successful)
            {
                return BadRequest(new { error = "Cannot cancel order" });
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Filter(OrderFilters orderFilters)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var orders = await _orderService.GetOrderListAsync(Guid.Parse(user.Id), orderFilters);

            OrderListViewModel orderList = new OrderListViewModel()
            {
                Orders = orders
            };

            return View("Index", orderList);
        }

        public IActionResult UpdateAddress()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("UpdateAddress")]
        public async Task<IActionResult> UpdateAddress(Address address)
        {
            address.Id = Guid.NewGuid();

            ModelState.Clear();
            bool validationResult = TryValidateModel(address);

            if (validationResult)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                await _userService.UpdateUserAddressAsync(user, address);

                return View("Add", address);
            }
            else
            {
                return View(address);
            }
        }

        public IActionResult SetNewAddress()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("SetNewAddress")]
        public async Task<IActionResult> SetNewAddress(Address address)
        {
            address.Id = Guid.NewGuid();

            ModelState.Clear();
            bool validationResult = TryValidateModel(address);

            if (validationResult)
            {
                bool succedeed = await _userService.AddAddressAsync(address);
                if (!succedeed)
                {
                    return BadRequest(new { error = "Could not set address" });
                }

                return View("Add", address);
            }
            else
            {
                return View(address);
            }
        }
    }
}

StoreWebsite/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreWebsite.Models;
using StoreWebsite.Services;

namespace StoreWebsite.Controllers
{
    public class ProductsController : Controller
    {
        readonly IProductService _productService;

        public ProductsController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetAllProductsAsync();

            var model = new ProductListViewModel()
            {
                Products = products
            };

            return View(model);
        }

        [Authorize(Policy = "Management")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = "Management")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            if (product.ImageFile == null)
                return BadRequest(new { error = "Invalid image" });

            string ext = Path.GetExtension(product.ImageFile.FileName).ToLower();

            if (ext != ".jpg" && ext != ".tiff" && ext != ".gif" && ext != ".jpeg" && ext != ".png" && ext != ".bmp")
                return BadRequest(new { error = "Invalid image format" });

            if (ModelState.IsValid)
            {
                bool result = await _productService.AddProductAsync(product);
                if (!result)
                    return BadRequest(new { error = "Could not add item" });
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [Authorize(Policy = "Management")]
        public async Task<IActionResult> Delete(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(product);
        }

        [Authorize(Policy = "Management")]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);

            if (ModelState.IsValid)
            {
                bool result = await _productService.RemoveProductAsync(product);
                if (!result)
                    return BadRequest(new { error = "Could not add item" });
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [Authorize(Policy = "Management")]
        public async Task<IActionResult> Edit(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(product);
        }

        [Authorize(Policy = "Management")]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditConfirmed(Product product)
        {
            if (ModelState.IsValid)
            {
                bool result = await _productService.EditProductAsync(product);
                if (!result)
                    return BadRequest(new { error = "Could not add item" });
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [Authorize(Policy = "Management")]
        public async Task<IActionResult> EditImage(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(product);
        }

        [Authorize(Policy = "Management")]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("EditImage")]
        public async Task<IActionResult> EditImageConfirmed(Product product)
        {
            if (product.ImageFile == null)
                return BadRequest(new { error = "Invalid image" });

            string ext = Path.GetExtension(product.ImageFile.FileName).ToLower();

            if (ext != ".jpg" && ext != ".tiff" && ext != ".gif" && ext != ".jpeg" && ext != ".png" && ext != ".bmp")
                return BadRequest(new { error = "Invalid image format" });

            bool result = await _productService.EditProductImageAsync(product);
            if (!result)
                return BadRequest(new { error = "Could not edit image" });
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(product);
        }
    }
}

StoreWebsite/ViewComponents/Cart/ItemDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StoreWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreWebsite.ViewComponents
{
    public class ItemDetailsViewComponent: ViewComponent
    {
        private readonly IProductService _productService;

        public ItemDetailsViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(product);
        }
    }
}

StoreWebsite/ViewComponents/Cart/OrderFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StoreWebsite.Models;
using StoreWebsite.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreWebsite.ViewComponents
{
    public class OrderFormViewComponent: ViewComponent
    {
        private readonly IProductService _productService;

        public OrderFormViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid Id)
        {
            var product = await _productService.GetProductAsync(Id);
            return View(new OrderDetails()
            {
                Product = product,
                ProductId = Id
            });
        }
    }
}

StoreWebsite/Views/Cart/Add.cshtml
@{
    ViewData["Title"] = "Add to cart";
}

<h2></h2>

@await Component.InvokeAsync("ItemDetails", new { Id = Model.Id })
@await Component.InvokeAsync("OrderForm", new { Id = Model.Id })

StoreWebsite/Views/Cart/Edit.cshtml
@model StoreWebsite.Models.CartItem

@{
    ViewData["Title"] = "Edit";
}
<h3>You are modyfying: </h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @Html.LabelFor(model => model.Product.Name)
                <h4>@Html.DisplayFor(model => model.Product.Name)</h4>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Product.Price)
                <h4> @Html.DisplayFor(model => model.Product.Price)$</h4>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" value="@Model.Quantity" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreWebsite/Views/Cart/Index.cshtml
@model CartViewModel

@{
    ViewData["Title"] = "Cart";
}

<h2>Cart</h2>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CartItems.First().Product.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartItems.First().Product.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartItems.First().Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CartItems.First().TotalPrice)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CartItems)
        {
            <tr>
                <td>
                    @{
                        var base64 = Convert.ToBase64String(item.Product.Image.Image);
                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img src="@imgSrc" height="100" />
                </td>
                <td>
                    <a asp-controller="Products" asp-action="Details" asp-route-id="@item.ProductId">@item.Product.Name</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)$
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity) |
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)$
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Product details</a> |
                    <a asp-action="Remove" asp-route-id="@item.Id">Remove from cart</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td />
            <td />
            <td />
            <td>
                <h4>
                    @Html.DisplayNameFor(model => model.TotalValue):
                </h4>
            </td>
            <td>
                <h4> @Html.DisplayFor(model => model.TotalValue)$</h4>
            </td>
            <td />
        </tr>
    </tfoot>
</table>

<input type="button" value="Checkout" class="btn btn-default" onclick="window.location='@Url.Action("ChooseAddress", "Orders")'" />